[project]
name = "math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "celery>=5.6.3",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "openai>=3.14.1",
    "pgvector>=0.5.0",
    "psycopg2>=2.9.13",
    "psycopg2-binary>=2.9.13",
    "redis>=8.1.0",
    "sentence-transformers>=6.1.0",
    "sqlalchemy>=2.0.54",
    "tiktoken>=0.14.0",
    "uvicorn[standard]>=0.53.0",
]
