"""add chapter_part table and part_id link

Revision ID: e42ff3d4b3bf
Revises: 4d99c60c5b4c
Create Date: 2026-09-24 12:56:38.804881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42ff3d4b3bf'
down_revision: Union[str, Sequence[str], None] = '4d99c60c5b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_part',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'order_index', name='uq_chapter_part_order')
    )
    op.create_index(op.f('ix_chapter_part_document_id'), 'chapter_part', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_part_document_id'), table_name='chapter_part')
    op.drop_table('chapter_part')
    # ### end Alembic commands ###
