"""add token usage columns to message

Revision ID: 09a650934b11
Revises: 480c9dfd8ff0
Create Date: 2026-10-04 14:41:37.405658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a650934b11'
down_revision: Union[str, Sequence[str], None] = '480c9dfd8ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('prompt_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('message', sa.Column('completion_tokens', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'completion_tokens')
    op.drop_column('message', 'prompt_tokens')
    # ### end Alembic commands ###
