"""added oauth and user tables

Revision ID: d7f1c3d0af0f
Revises: 118ab963539e
Create Date: 2026-09-30 10:20:07.797987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f1c3d0af0f'
down_revision: Union[str, Sequence[str], None] = '118ab963539e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunk_content_fts'), table_name='document_chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunk_embedding_hnsw'), table_name='document_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunk_embedding_hnsw'), 'document_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunk_content_fts'), 'document_chunk', [sa.literal_column("to_tsvector('french'::regconfig, content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
